services:
  esp32-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idf
    ports:
      - "2222:22"
    # Grant hardware access
    privileged: true
    tty: true
    stdin_open: true
    # restart: always
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0" # Map the ESP32 port
    volumes:
      - ../..:/workspaces:rw
      - /home/marcpawl/.ssh/id_rsa.pub:/root/.ssh/authorized_keys

